spring:
  datasource:
    username: root
    password: bhr050219
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?serverTimezone=UTC
  application:
    name: RecyclingBook
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: 192.168.136.131
      port: 6379
      database: 0
      timeout: 100000
      lettuce:
        pool:
          max-active: 16
          max-wait: -1
          max-idle: 5
          min-idle: 0
server:
  port: 8080

logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**.xml




